#!/bin/sh
export QT_QPA_PLATFORM=wayland
# start sway
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export WLR_NO_HARDWARE_CURSORS=1

export QT_AUTO_SCREEN_SCALE_FACTOR=1

export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export GDK_BACKEND=wayland
export XDG_CURRENT_DESKTOP=sway
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export MOZ_ENABLE_WAYLAND=1
export WLR_NO_HARDWARE_CURSORS=1

sway -c ~/.config/sway/config
